services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: biblehaus
      POSTGRES_USER: biblehaus
      POSTGRES_PASSWORD: biblehaus
    volumes:
      - ./sql:/var/lib/postgresql/data
    networks:
      - biblehaus

  web:
    image: ghcr.io/digitalwowro/biblehaus:latest
    pull_policy: always
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://biblehaus:biblehaus@db:5432/biblehaus
    volumes:
      - ./tts:/app/.cache/tts
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - biblehaus

networks:
  biblehaus:
    internal: true

